# Generated by Django 5.1.7 on 2025-03-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('post_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('sentiment_score', models.FloatField(null=True)),
                ('engagement_score', models.FloatField(null=True)),
                ('tags', models.JSONField(null=True)),
            ],
        ),
    ]
