# Generated by Django 5.1.7 on 2025-04-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_samplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='link',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
