# Generated by Django 5.1.7 on 2025-04-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rawdata_raw_response_alter_rawdata_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('country', models.CharField(db_index=True, max_length=50)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['country', 'category'], name='api_process_country_4b855f_idx'), models.Index(fields=['country', 'published_date'], name='api_process_country_169fc0_idx')],
            },
        ),
    ]
