# Generated by Django 5.1.7 on 2025-04-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_processeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
