# Generated by Django 5.1.7 on 2025-04-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_rawdata_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='link',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
