# Generated by Django 5.1.7 on 2025-05-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_rawdata_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True, unique=True),
        ),
    ]
